### ISSUE TITLE
No "STIRRUP_DIM_STYLE" and  "STIRRUP_LEN_STYLE" in file "Template.dxf"

### ISSUE THREAD

**Issue by chakkreetiya** [ebrahimraeyat/pyconcrete#1]
> raise DXFTableEntryError(name)
>    ezdxf.lldxf.const.DXFTableEntryError: STIRRUP_DIM_STYLE
> 
> raise DXFTableEntryError(name)
>    ezdxf.lldxf.const.DXFTableEntryError: STIRRUP_LEN_STYLE

**Comment by ebrahimraeyat** [comment]
thanks. fixed.

 d8b39f0

**Comment by chakkreetiya** [comment]
Thank you.
